### PR TITLE
Updated README.md to modern template. Added readthedocs.io for documentation.  Updated Logo

### PR DESCRIPTION
**Pull request by jhiggason**
I've worked very hard on a new README.md and setting up a proper manual for our Common Robotics Platform.  The pull request still needs work adding in information into the main readme and the docs 4 main pages. (intro.rst, hardware.rst, software.rst, testing.rst)  

Search for "TODO" to find things that need updating on the main README.md.  
When changes are made to the above 4 .rst files- readthedocs.io automatically builds the new sphinx pages.  I think we should move the readthedocs.io to a PARTS account but this will work for the time being.  

Would love to hear feedback from you all about what you like and don't like! 

See the full changes here:  https://github.com/jhiggason/PARTS_common_platform/tree/master

### CODE REVIEW

**Comment by jhiggason** [comment]
- [ ] Add R to logo 
- [ ] Ensure Est. Date is correct on logo
- [ ] Fix the P on logo

**Comment by jhiggason** [comment]
I added my working sbus_test as it's own folder in "firmware"  I added a readme and explained the code.

**Comment by jmd5** [comment]
Hi Jeff H, I had a look and this all looks good to me.  Shall we go ahead and merge it into the master branch?

**Comment by jhiggason** [comment]
@jmd5 I got the logo fixed on there. I think we are good to merge at this point.

**Review by jmd5 — APPROVED** [review]
Looks great to me!

**Pull request merged**
